version: '2.1'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "${PROJECT_ROOT}:/var/www/html:ro"
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
  
  php:
    build: .
    expose: 
      - "9000"
    volumes: 
      - "${PROJECT_ROOT}:/var/www/html"
    depends_on:
      - db

  db:
    image: mariadb:latest
    ports: 
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PW}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PW}"

volumes:
  db_data:
